name: Check

on:
  push:
  pull_request:

jobs:
  deploy:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: npm run build
